- year: 2019
  data:
  - name: Co-organizer of a data science workshop in the University of Washington.
- year: 2018
  data:
  - name: Program Committee of Foundations of Computer Science (FOCS 2018)
  - name: Co-organizer of a data science workshop in the University of Wisconsin.
- year: 2017
  data:
  - name: Program Committee of Symposium on Discrete Algorithms (SODA 2017)
  - name: Co-organizer of a workshop in The 49th Annual ACM Symposium on the Theory of Computing (STOC 2017)
  - name: Program Committee of International Workshop on Randomization and Computation (RANDOM 2017)
- year: 2016
  data:
  - name: Co-organizer of three sessions in The fifth International Conference on Continuous Optimization (ICCOPT 2016)
